[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"

[environments.staging]
[environments.staging.variables]
NODE_ENV = "staging"
